project:
  type: website

website:
  title: "Admir Junior"
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About me
      - href: embeded_resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects and tutorials
      - href: publications.qmd
        text: Publications
    
  page-footer:
    center: |
      [Contact Admir Junior](mailto:admircjunior@gmail.com)
    left: |
      Made with [Quarto](https://quarto.org/)
    right: |
      [Github Code Repo](https://github.com/xxxx)
    background: dark
    

format:
  html:
    theme: 
      light: united
      dark: [united, assets/custom_dark.scss]
    css: styles.css
    toc: true

editor: visual

